server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./data/exemplo
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enable: true
      path: /h2-console

