server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./data/exemplo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

