INSERT INTO state ( id, uf, name) VALUES (1, 'AC', 'Acre');
INSERT INTO state ( id, uf, name) VALUES (2, 'AL', 'Alagoas');
INSERT INTO state ( id, uf, name) VALUES (3, 'AM', 'Amazonas');
INSERT INTO state ( id, uf, name) VALUES (4, 'AP', 'Amapá');
INSERT INTO state ( id, uf, name) VALUES (5, 'BA', 'Bahia');
INSERT INTO state ( id, uf, name) VALUES (6, 'CE', 'Ceará');
INSERT INTO state ( id, uf, name) VALUES (7, 'DF', 'Distrito Federal');
INSERT INTO state ( id, uf, name) VALUES (8, 'ES', 'Espírito Santos');
INSERT INTO state ( id, uf, name) VALUES (9, 'GO', 'Goias');
INSERT INTO state ( id, uf, name) VALUES (10, 'MA', 'Maranhão');
INSERT INTO state ( id, uf, name) VALUES (11, 'MG', 'Minas Gerais');
INSERT INTO state ( id, uf, name) VALUES (12, 'MT', 'Mato Grosso');
INSERT INTO state ( id, uf, name) VALUES (13, 'MS', 'Mato Grosso do Sul');
INSERT INTO state ( id, uf, name) VALUES (14, 'PA', 'Para');
INSERT INTO state ( id, uf, name) VALUES (15, 'PB', 'Paraíba');
INSERT INTO state ( id, uf, name) VALUES (16, 'PE', 'Pernanmbuco');
INSERT INTO state ( id, uf, name) VALUES (17, 'PI', 'Piauí');
INSERT INTO state ( id, uf, name) VALUES (18, 'PR', 'Paraná');
INSERT INTO state ( id, uf, name) VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO state ( id, uf, name) VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO state ( id, uf, name) VALUES (21, 'RO', 'Rondônia');
INSERT INTO state ( id, uf, name) VALUES (22, 'RR', 'Rorâima');
INSERT INTO state ( id, uf, name) VALUES (23, 'RS', 'Rio Grande do Sul');
INSERT INTO state ( id, uf, name) VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO state ( id, uf, name) VALUES (25, 'SE', 'Sergipe');
INSERT INTO state ( id, uf, name) VALUES (26, 'SP', 'São Paulo');
INSERT INTO state ( id, uf, name) VALUES (27, 'TO', 'Tocantins');